// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0cDXUboRzzfwci5cqZPEwTpBXNsqQIDk',
    appId: '1:271660145428:web:074120f90044859a508001',
    messagingSenderId: '271660145428',
    projectId: 'flutter-homework-f34cb',
    authDomain: 'flutter-homework-f34cb.firebaseapp.com',
    storageBucket: 'flutter-homework-f34cb.appspot.com',
    measurementId: 'G-XD1WN9PZRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_FBoJqLJyoXi7dq3K_jx7lJvPJR16kw',
    appId: '1:271660145428:android:7f885cb23989100f508001',
    messagingSenderId: '271660145428',
    projectId: 'flutter-homework-f34cb',
    storageBucket: 'flutter-homework-f34cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA04oYs8z27JOrzPa9Es7YkZA0ex3NTVyo',
    appId: '1:271660145428:ios:7f57376705b994d6508001',
    messagingSenderId: '271660145428',
    projectId: 'flutter-homework-f34cb',
    storageBucket: 'flutter-homework-f34cb.appspot.com',
    iosClientId: '271660145428-gh4gjs75mpkk7dc85tlbdp4p8kniii74.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA04oYs8z27JOrzPa9Es7YkZA0ex3NTVyo',
    appId: '1:271660145428:ios:d431981f31ef436e508001',
    messagingSenderId: '271660145428',
    projectId: 'flutter-homework-f34cb',
    storageBucket: 'flutter-homework-f34cb.appspot.com',
    iosClientId: '271660145428-gkeja2am0hhp8a19vc9rs63jkq7ehi6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicCalculator.RunnerTests',
  );
}
